apiVersion: logging.openshift.io/v1
kind: Elasticsearch
metadata:
  name: {{ .Values.instanceName }}
  namespace: {{ .Values.namespace }}
spec:
    managementState: Managed
    indexManagement: {}
    nodes:
    - nodeCount: {{ .Values.nodeCount }}
      resources: {}
      roles:
        - master
        - client
        - data
      storage:
        storageClassName: "gp2"
        size: 500Gi
      nodeSelector: {}
      tolerations: []
      proxyResources: {}
    
    nodeSpec:
        resources:
            limits:
                memory: 16Gi
            requests:
                cpu: 200m
                memory: 16Gi
        proxyResources:
            limits:
                memory: 100Mi
            requests:
                cpu: 100m
                memory: 100Mi 

    redundancyPolicy: {{ .Values.redundancyPolicy }}

