apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dist-trace-data-pvc
  labels:
    type: dist-trace-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
    selector:
      matchLabels:
        type: dist-trace-data-pv