apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "review-mtls-policy"
  namespace: "istio-samples"
spec:
  selector:
    matchLabels:
      app: reviews
  mtls:
    mode: STRICT